name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  header:
    description: 'The header of your README.md.'
    required: true
    default: ''
  subhead:
    description: 'The subheader of your README.md.'
    required: false
    default: ''
  footer:
    description: 'The footer of your README.md.'
    required: false
    default: ''
  path:
    description: 'Path of your README.md file.'
    required: false
    default: 'README.md'
  repoCount:
    description: 'Number of repositories to load.'
    required: false
    default: '6'
  reposPerRow:
    description: 'Number of repositories to load per row.'
    required: false
    default: '3'
  customReadmeFile:
    description: "Customise the README.md file format without forking this repository. Read more on this repository's README.md"
    required: false
    default: |
      ## ${header}
      
      ${subhead}

      ---
      
      ${repoTable}
      
      ---
      
      ${footer}

outputs:
  repositories:
    description: 'Array of recent repositories to be displayed on your profile README.md.'

runs:
  using: 'node12'
  main: 'index.js'